apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networkpolicy.yaml
  - node22-imagestream.yaml
  - imagestream.yaml
  - buildconfig.yaml
  - deployment.yaml
  - route.yaml
  - service.yaml

# generatorOptions:
#   disableNameSuffixHash: true

# configMapGenerator:
#   - name: run-config
#     files:
#       - config.yaml=run.yaml
